name: go
on:
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - name: Lint
        uses: golangci/golangci-lint-action@v6
      - name: Test
        run: make test
      - name: Build
        run: make build
